version: "3.8"
services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:starter
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "9000:9000"
    volumes:
      - .:/app/medusa
      - node_modules:/app/medusa/node_modules
    networks:
      - medusa

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - medusa

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - medusa

  minio:
    image: quay.io/minio/minio:RELEASE.2023-06-29T05-12-28Z
    command: server /data --console-address ":9001"
    expose:
      - "9001:9000"
      - "9090:9001"
    volumes:
      - storage:/data
    networks:
      - medusa
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3


volumes:
  node_modules:
  storage:
  cache:

networks:
  medusa:
    driver: bridge
